[package]
name = "hello-world"
version = "0.1.0"
authors = ["Melchior Moulin <melchior.moulin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.1.4"

[lib]
crate-type = ["cdylib"]
