name: Rust

on: [push]

jobs:
  rust-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target wasm32-unknown-unknown
      - uses: actions/upload-artifact@v2
        with:
          name: hello_wold.wasm
          path: target/wasm32-unknown-unknown/release/hello_world.wasm